---
title: "readme"
output: html_document
date: "2024-06-17"
---

# "ChemCheck" application - chemical compounds search engine

If you want to receive basic information about different chemical compounds, this application is for you! The information comes from PubChem [1] API, so all data is verified.

### This application provides:

-   image of a chemical compound
-   short description
-   molar mass
-   chemical formula
-   canonical SMILES
-   exact molar mass
-   XLogP - measure of hydrophilicity or hydrophobicity of a molecule
-   TPSA - topological polar surface area
-   number of hydrogen bond donors
-   number of hydrogen bond acceptors
-   number of rotatable bonds

### How to use this application?

1.  Start the app
2.  Write a compound name (e.g. glucose) or a chemical formula (e.g. CO2)
3.  Click "Search" button
4.  Ta-Daaaa! Now you can read about your chosen compound

Disclaimer: If your compound is not in PubChem, the app will return the information: "No compound found", and all properties will have value "N/A" (not found). Don't worry, you can search again! Maybe it has different name in PubMed?

### Some interesting, fun and mind-boggling compounds - check them yourself!

-   Nanokid (this is the best one, no kidding)
-   Olympicene
-   Fullerene
-   Octanitrocubane
-   Fenestrane
-   Maitotoxin
-   Cyclodextrin

#### Documentation

The source code has comments that explain how app is working.

#### Bibliography

[1] Kim S, Chen J, Cheng T, et al. PubChem 2023 update. Nucleic Acids Res. 2023;51(D1):D1373--D1380. <doi:10.1093/nar/gkac956>
